### PR TITLE
Update app/src

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by licaon-kter** [comment]
How did you create this PR? Never do that again, we got spammed for every commit ffs.

Also, what is this about?

**Comment by licaon-kter** [comment]
@SamSanuch Please stop commiting like this!

**Comment by licaon-kter** [comment]
Did you just diff Termux and NeoTerm, WHY?

**Comment by licaon-kter** [comment]
@zt515 close this

**Comment by ghost** [comment]
Shit i have just forked NeoTerm and committed changes but i forget to not compare with mater branch
You can close this PR as this is not needed and of course this PR is not for neoterm developement purposes!

**Pull request closed without merging**
